#!/usr/bin/env node
// install.mjs — the ONLY file in this kit that changes anything, and it says everything first.
//
//   node install.mjs ~/your/projects              DRY RUN: the complete, literal list of changes
//   node install.mjs ~/your/projects --apply      do exactly that list — this is the one consent
//   node install.mjs --global-hooks ...           machine-wide hooks instead of per-repo (opt-in)
//   node install.mjs --uninstall                  replay the manifest in reverse; restore everything
//
// Every other file in this kit reads, counts, and prints. This one wires the mechanical half of
// SETUP.md so a person who is not sitting next to us gets it right the first time. The rules it
// runs under are not negotiable, because two shipped products died of per-step confirmation
// friction and a third class of tool dies of hidden writes:
//
//   1. NOTHING IS HIDDEN. The dry run prints every path it will touch, every git config key with
//      its CURRENT value, and the exact bytes it will write. What you read is what happens.
//   2. ONE CONSENT. `--apply` is it. No per-step prompts — the disclosure already happened, and
//      asking again on every file teaches people to stop reading before they stop clicking.
//   3. EVERYTHING IS REVERSIBLE. Every change lands in an append-only manifest, `--uninstall`
//      replays it in reverse, and UNDO.md says how to do the same by hand if this file is gone.
//   4. MECHANICAL ONLY. Judgment stays with the human. Concretely, this file will NEVER:
//        - write a `verify` command for a project. It may SUGGEST one when it sees a test
//          script, but a verify this kit invented is a verify nobody trusts — and a wrong one
//          turns the whole board green for free. The human writes it, or it stays null.
//        - set a lane other than `tier1`. A registry generated by a machine that has never seen
//          these projects is nothing but doubt, and doubt resolves to tier1.
//        - delete anything, commit, push, or touch a byte of project source.
//        - make a network request. There is no network call in this file.
//
// WHERE THINGS LAND. Durable state goes to a home folder OUTSIDE the clone (~/.five-hats, or
// $FIVE_HATS_HOME): the manifest, UNDO.md, and a copy of every baseline JSON found here. The
// baseline is the only honest "before" a person will ever get, and it used to live inside the
// clone — where one `rm -rf && git clone` destroyed it. Preserving it is an install step
// precisely because nobody does it by hand.
//
// THE HOOK. Per-repo by default; `--global-hooks` is the machine-wide opt-in, and it first
// enumerates which repos' own hooks would go dark, because a replaced hooks path fails silently.
// A pre-existing global core.hooksPath is never replaced — this repo already shipped the bug
// where setting the path clobbered a value nobody had backed up, once, and once is the quota.
// The hook file itself must be unable to brick a machine: a GUI git client ships a minimal PATH,
// and a hook that exits non-zero when it cannot find node fails EVERY commit on the machine for
// a person who has no idea why. So the hook hunts for node, and when it truly cannot find one it
// steps aside LOUDLY — the commit proceeds, the message says it was not scanned, and nothing is
// ever bricked. A guard that fails open with a shout beats a machine that fails shut in silence.

import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { spawnSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { KIT_VERSION } from './kit-version.mjs';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const flag = (n) => argv.includes(`--${n}`);
const val = (n) => { const i = argv.indexOf(`--${n}`); return i === -1 ? null : argv[i + 1]; };
const positional = argv.filter((a, i) => !a.startsWith('--') && !String(argv[i - 1] || '').startsWith('--'));

const APPLY = flag('apply');
const GLOBAL = flag('global-hooks');
// $FIVE_HATS_HOME exists so the verify can run this whole file against a sandbox without
// touching the real home. It is also the honest escape hatch for anyone who wants kit state
// somewhere specific.
const HOME_DIR = process.env.FIVE_HATS_HOME || path.join(os.homedir(), '.five-hats');
const MANIFEST = path.join(HOME_DIR, 'install-manifest.jsonl');
const UNDO = path.join(HOME_DIR, 'UNDO.md');
const REG_PATH = path.resolve(val('registry') || path.join(HERE, 'projects.json'));

const B = (s) => `\x1b[1m${s}\x1b[0m`;
const DIM = (s) => `\x1b[2m${s}\x1b[0m`;
const sha = (buf) => crypto.createHash('sha256').update(buf).digest('hex');
const fwd = (p) => p.replace(/\\/g, '/');
const readIf = (p) => { try { return fs.readFileSync(p, 'utf8'); } catch { return null; } };

// git, invoked directly — never through a shell, so nothing here can run anything but git.
const git = (args, cwd) => {
  const r = spawnSync('git', args, { cwd: cwd || HERE, encoding: 'utf8' });
  return r.status === 0 ? (r.stdout || '').trim() : null;
};

// ---------------------------------------------------------------------------------------------
// The hook, exactly as written into every repo. Same bytes everywhere; LF only, because git
// runs hooks through sh and a CRLF shebang is an unexplained "cannot exec" on two of the three
// platforms this kit promises.
// ---------------------------------------------------------------------------------------------
function hookText(mode) {
  const guard = fwd(path.join(HERE, 'bin', 'secret-guard.mjs'));
  const node = fwd(process.execPath);
  return `#!/bin/sh
# five-hats secret-guard (${mode}) — kit ${KIT_VERSION}
# Installed by install.mjs. Manifest: ${fwd(MANIFEST)}
# It does one thing: blocks a git operation that would put a secret into history.
# Remove it: delete this file, or run \`node ${fwd(path.join(HERE, 'install.mjs'))} --uninstall\`.
#
# WHY it hunts for node and then steps ASIDE instead of blocking: a GUI git client ships a
# minimal PATH, and a hook that exits non-zero when it cannot find its runtime fails EVERY
# commit on the machine, for a person with no terminal open to read why. When the runtime is
# genuinely missing this hook lets the operation through and SAYS SO — loudly, every time —
# because an unscanned commit you were told about beats a machine you can no longer commit on.
skip () {
  echo "five-hats: secret scan SKIPPED — $1." >&2
  echo "five-hats: this ${mode === 'pre-push' ? 'push' : 'commit'} was NOT checked for secrets. It was NOT blocked." >&2
  echo "five-hats: to remove this hook entirely, delete: $0" >&2
  exit 0
}
GUARD='${guard}'
if [ -n "$FIVE_HATS_NODE" ]; then
  # An explicit pin that is broken must not silently fall back to some other node — you pinned
  # it, it is gone, you get told.
  NODE="$FIVE_HATS_NODE"
  [ -x "$NODE" ] || skip "FIVE_HATS_NODE points at $NODE, which is not executable"
else
  NODE='${node}'
  [ -x "$NODE" ] || NODE="$(command -v node 2>/dev/null || true)"
  if [ -z "$NODE" ]; then
    for c in /usr/local/bin/node /opt/homebrew/bin/node /usr/bin/node "$PROGRAMFILES/nodejs/node.exe"; do
      [ -x "$c" ] && NODE="$c" && break
    done
  fi
  [ -n "$NODE" ] || skip "no node runtime could be found on this machine"
fi
[ -e "$GUARD" ] || skip "the five-hats kit is no longer at $GUARD (moved or re-cloned elsewhere)"
case "$("$NODE" --version 2>/dev/null)" in
  v[0-9].*|v1[0-7].*) skip "node $("$NODE" --version 2>/dev/null) is older than the 18 this kit needs" ;;
esac
# The PULSE — the staleness nag. This is the trigger the whole kit turns on: it is why the
# checks happen without anyone deciding to run them. Cheap, silent when fresh, and it CANNOT
# silently die the way a cron job can. Never blocks: a nag that can fail a commit is a nag
# nobody keeps.
# --registry is PINNED to the one this repo was installed with. Without it pulse fell back to
# the kit's own projects.json, so committing in one repo printed warnings about somebody else's
# projects entirely — a finding attached to the wrong thing is worse than no finding, because
# the reader goes looking in a place that was never the problem.
"$NODE" '${fwd(path.join(HERE, 'pulse.mjs'))}' --quiet --registry '${fwd(REG_PATH)}' 2>/dev/null || true
exec "$NODE" "$GUARD" --${mode === 'pre-push' ? 'push' : 'staged'}
`;
}
const HOOK_MARK = 'five-hats secret-guard';

// ---------------------------------------------------------------------------------------------
// Discovery — same markers as start.mjs, same refusal when nothing project-shaped exists,
// because installing into the wrong folder produces confident nonsense with hooks in it.
// ---------------------------------------------------------------------------------------------
const MARKERS = ['.git', 'package.json', 'pyproject.toml', 'go.mod', 'Cargo.toml', 'Gemfile', 'requirements.txt'];
function discover(target) {
  let entries;
  try { entries = fs.readdirSync(target, { withFileTypes: true }); } catch { return null; }
  return entries
    .filter((d) => d.isDirectory() && !d.name.startsWith('.') && d.name !== 'node_modules')
    .map((d) => path.join(target, d.name))
    .filter((p) => MARKERS.some((m) => fs.existsSync(path.join(p, m))));
}

// Suggest — never write. `npm test` that is npm's own "no test specified" stub is not a verify,
// it is the absence of one wearing the name.
function suggestVerify(dir) {
  const pkg = readIf(path.join(dir, 'package.json'));
  if (pkg) {
    try {
      const t = (JSON.parse(pkg).scripts || {}).test;
      if (t && !/no test specified/i.test(t)) return 'npm test';
    } catch { /* unparseable package.json is its own finding, not this one's */ }
  }
  if (fs.existsSync(path.join(dir, 'pytest.ini')) || fs.existsSync(path.join(dir, 'tox.ini'))
    || /\[tool\.pytest/.test(readIf(path.join(dir, 'pyproject.toml')) || '')) return 'pytest';
  if (fs.existsSync(path.join(dir, 'go.mod'))) return 'go test ./...';
  if (fs.existsSync(path.join(dir, 'Cargo.toml'))) return 'cargo test';
  return null;
}

// ---------------------------------------------------------------------------------------------
// Manifest — append-only. Recorded BEFORE each write, so a crash mid-apply leaves a manifest
// that over-claims rather than a change nobody recorded; uninstall verifies every entry against
// the disk before undoing it, so an over-claim costs nothing and an unrecorded change is
// impossible.
// ---------------------------------------------------------------------------------------------
function record(entry) {
  fs.mkdirSync(HOME_DIR, { recursive: true });
  fs.appendFileSync(MANIFEST, `${JSON.stringify({ v: KIT_VERSION, at: new Date().toISOString(), ...entry })}\n`);
}
function readManifest() {
  const t = readIf(MANIFEST);
  if (t === null) return { entries: [], corrupt: 0 };
  const entries = []; let corrupt = 0;
  for (const line of t.split('\n').filter(Boolean)) {
    try { entries.push(JSON.parse(line)); } catch { corrupt += 1; }
  }
  return { entries, corrupt };
}

// ---------------------------------------------------------------------------------------------
// UNINSTALL — the manifest in reverse. Three guards, each because the alternative deletes
// somebody's work: a file is removed only if its bytes still match what was written (or, for a
// hook, it still carries our marker); a config key is restored only if it still holds our
// value; anything a human changed since install is LEFT IN PLACE and named.
// ---------------------------------------------------------------------------------------------
function uninstall() {
  console.log(B(`\n  Five Hats — uninstall (kit ${KIT_VERSION})\n`));
  const { entries, corrupt } = readManifest();
  if (!entries.length) {
    console.log('  Nothing recorded as installed — no manifest at');
    console.log(`  ${MANIFEST}`);
    console.log('  Nothing to undo.\n');
    process.exit(0);
  }
  if (corrupt) {
    console.log(`  ! ${corrupt} manifest line(s) could not be parsed. Whatever they recorded`);
    console.log('    cannot be undone from here — check UNDO.md for the by-hand list.\n');
  }
  const done = (m) => console.log(`  undone   ${m}`);
  const left = (m) => console.log(`  LEFT     ${m}`);
  const handled = new Set();   // a path written twice is undone once, from its newest record
  const mkdirs = [];

  for (const e of [...entries].reverse()) {
    if (e.action === 'mkdir') { mkdirs.push(e.path); continue; }
    if (e.action === 'git-config-set') {
      const cur = git(['config', '--global', '--get', e.key]);
      if (cur !== e.value) { left(`git config ${e.key} — now '${cur ?? '(unset)'}', not ours; not touched`); continue; }
      if (e.prev == null) git(['config', '--global', '--unset', e.key]);
      else git(['config', '--global', e.key, e.prev]);
      done(`git config --global ${e.key} restored to ${e.prev == null ? '(unset)' : `'${e.prev}'`}`);
      continue;
    }
    if (e.action === 'write' || e.action === 'copy') {
      const p = e.action === 'copy' ? e.to : e.path;
      if (handled.has(p)) continue;
      handled.add(p);
      if (!fs.existsSync(p)) { done(`${p} (already gone)`); continue; }
      const cur = fs.readFileSync(p);
      if (sha(cur) === e.sha256) { fs.unlinkSync(p); done(p); }
      else if (e.kind && e.kind.startsWith('hook') && cur.toString('utf8').includes(HOOK_MARK)) {
        fs.unlinkSync(p); done(`${p} (a newer version of our own hook)`);
      } else left(`${p} — changed since install; your edits, so not deleted`);
      continue;
    }
    left(`unknown manifest action '${e.action}' — not touched`);
  }

  // Our own bookkeeping goes last, then the dirs we made — deepest first, and only if empty,
  // so anything a human put inside the home survives the home.
  for (const f of [UNDO, MANIFEST]) { try { fs.unlinkSync(f); } catch { /* already gone */ } }
  for (const d of mkdirs.sort((a, b) => b.length - a.length)) {
    try { fs.rmdirSync(d); done(`${d} (empty, removed)`); }
    catch { if (fs.existsSync(d)) left(`${d} — not empty, not removed`); }
  }
  console.log('\n  Preserved baseline COPIES were removed with the rest; the originals in the');
  console.log('  kit folder were never touched by install or uninstall.\n');
  process.exit(0);
}

if (flag('uninstall')) uninstall();

// ---------------------------------------------------------------------------------------------
// PLAN — computed the same way for dry run and apply, from what is on disk right now. A step
// whose postcondition already holds is not proposed, which is the whole of idempotence: the
// second run proposes nothing because there is nothing left to propose.
// ---------------------------------------------------------------------------------------------
const target = path.resolve(positional[0] || '..');
const steps = [];       // { line, detail?, do() }
const skipped = [];     // named, with the reason — a silent skip is a hidden decision
const never = 'write a "verify" for any project · set any lane but tier1 · delete anything · '
  + 'commit, push, or touch project source · make a network request';

// -- step: the home ---------------------------------------------------------------------------
if (!fs.existsSync(HOME_DIR)) {
  steps.push({
    line: `CREATE   ${HOME_DIR}`,
    detail: 'the kit home: the manifest, UNDO.md, and preserved baselines live here — outside the clone',
    do() { fs.mkdirSync(HOME_DIR, { recursive: true }); record({ action: 'mkdir', path: HOME_DIR }); },
  });
}

// -- step: preserve every baseline ------------------------------------------------------------
// The before-picture is the one artifact that cannot be re-taken. It currently lands inside the
// clone, so a re-clone silently destroys the only honest "before" — this step is the fix.
const baseDir = path.join(HOME_DIR, 'baselines');
const baselineSrcs = [];
for (const d of [HERE, path.join(HERE, 'five-hats-report')]) {
  try {
    for (const f of fs.readdirSync(d)) {
      if (/^baseline-\d{4}-\d{2}-\d{2}\.json$/.test(f)) baselineSrcs.push(path.join(d, f));
    }
  } catch { /* no such dir yet */ }
}
let needBaseDir = false;
for (const src of baselineSrcs) {
  const buf = fs.readFileSync(src);
  const digest = sha(buf);
  let dst = path.join(baseDir, path.basename(src));
  const cur = fs.existsSync(dst) ? sha(fs.readFileSync(dst)) : null;
  if (cur === digest) continue;                                   // already preserved
  if (cur !== null) dst = path.join(baseDir, path.basename(src).replace(/\.json$/, `-${digest.slice(0, 8)}.json`));
  if (fs.existsSync(dst) && sha(fs.readFileSync(dst)) === digest) continue;
  needBaseDir = true;
  steps.push({
    line: `COPY     ${path.basename(src)} -> ${dst}`,
    detail: `${buf.length} bytes — the before-picture, kept where a re-clone cannot destroy it`,
    do() { fs.mkdirSync(baseDir, { recursive: true }); record({ action: 'copy', from: src, to: dst, sha256: digest }); fs.writeFileSync(dst, buf); },
  });
}
if (needBaseDir && !fs.existsSync(baseDir)) {
  steps.unshift({
    line: `CREATE   ${baseDir}`,
    do() { fs.mkdirSync(baseDir, { recursive: true }); record({ action: 'mkdir', path: baseDir }); },
  });
}

// -- step: the registry -----------------------------------------------------------------------
// Created only when absent; an existing registry is a human's work and is never edited. Every
// entry it writes has verify: null and lane tier1 — see the contract at the top of this file.
let regProjects = null;   // [name, dir] pairs the hook step will use
let regContent = null;
const existingReg = readIf(REG_PATH);
if (existingReg !== null) {
  try {
    const j = JSON.parse(existingReg);
    regProjects = Object.entries(j.projects || {}).map(([n, c]) => {
      let p = c.path || '';
      if (p.startsWith('~')) p = path.join(os.homedir(), p.slice(1));
      return [n, path.resolve(path.dirname(REG_PATH), p)];
    });
    // Registered-or-named: a project-shaped dir the registry misses is reported, not written.
    const known = new Set(regProjects.map(([, p]) => p));
    for (const p of discover(target) || []) {
      if (!known.has(p)) skipped.push(`${path.basename(p)} — project-shaped but not in your registry. Yours to add: node bin/project.mjs add ${path.basename(p)} --path ${p}`);
    }
  } catch {
    skipped.push(`${REG_PATH} exists but is not valid JSON — fix it by hand; nothing here will edit it`);
    regProjects = [];
  }
} else {
  const found = discover(target);
  if (found === null) { console.error(`\n  No such folder: ${target}\n`); process.exit(2); }
  if (!found.length) {
    console.log(`\n  ${B('Nothing here looks like a code project.')}`);
    console.log('  Point this at the folder that CONTAINS your projects, not at one project:');
    console.log('      node install.mjs ~/your/projects\n');
    console.log(DIM('  Refusing is the honest answer — an install into the wrong folder wires'));
    console.log(DIM('  hooks into nothing and calls it protection.\n'));
    process.exit(1);
  }
  const reg = { _scan_root: target, projects: {} };
  for (const p of found) {
    const s = suggestVerify(p);
    reg.projects[path.basename(p)] = {
      path: p, verify: null, lane: 'tier1',
      note: s ? `suggested verify: '${s}' — confirm it FAILS on a broken build, then move it into "verify" yourself`
        : 'no verify suggested — write the smallest command that would fail if this broke',
    };
  }
  regProjects = found.map((p) => [path.basename(p), p]);
  regContent = `${JSON.stringify(reg, null, 2)}\n`;
  steps.push({
    line: `WRITE    ${REG_PATH}`,
    detail: `${Buffer.byteLength(regContent)} bytes — shown in full below. Every verify is null (yours to write), every lane is tier1`,
    do() { record({ action: 'write', path: REG_PATH, kind: 'registry', sha256: sha(Buffer.from(regContent)), bytes: Buffer.byteLength(regContent) }); fs.writeFileSync(REG_PATH, regContent); },
  });
}

// -- step: the hooks --------------------------------------------------------------------------
const pre = hookText('pre-commit');
const push = hookText('pre-push');
const writeHook = (dest, text, kindTag) => ({
  line: `WRITE    ${dest}`,
  detail: `${Buffer.byteLength(text)} bytes — the hook, shown once below (same bytes everywhere)`,
  do() {
    record({ action: 'write', path: dest, kind: kindTag, sha256: sha(Buffer.from(text)), bytes: Buffer.byteLength(text) });
    fs.writeFileSync(dest, text);
    try { fs.chmodSync(dest, 0o755); } catch { /* Windows has no execute bit; sh runs it anyway */ }
  },
});

// Repos whose own hooks a global path would silence — enumerated BEFORE anyone consents,
// because a replaced hook does not fail, it just stops happening.
const reposWithOwnHooks = [];
const hookTargets = [];
for (const [name, dir] of regProjects || []) {
  // ASK GIT, do not look for a folder — the same fix drift needed, which was never carried here.
  // A project inside a larger repository has no .git of its own and is perfectly versioned; the
  // folder test skipped EVERY subdirectory of a monorepo, so the guard was wired to nothing and
  // MAINTAINER stayed uncovered after a successful-looking install. Caught by a dry run against a
  // real monorepo before anything was written, which is the entire reason the dry run exists.
  const topLevel = git(['rev-parse', '--show-toplevel'], dir);
  if (!topLevel) {
    skipped.push(`${name} — not under version control at all, so there is no hook to wire. `
      + 'drift reports this as SERIOUS; it is the bigger problem and no hook would fix it');
    continue;
  }
  const gitDirRoot = path.resolve(topLevel);
  const dotGit = path.join(gitDirRoot, '.git');
  if (path.resolve(dir) !== gitDirRoot) {
    // One repo, several project folders. The hook belongs to the REPO, not to each folder, and
    // wiring it once is correct — say which repo so nobody wonders where the hook went.
    skipped.push(`${name} — inside the ${path.basename(gitDirRoot)} repository; `
      + 'the hook is wired once on that repo and covers this folder too');
    if (hookTargets.some(([, d]) => d === gitDirRoot)) continue;
    hookTargets.push([path.basename(gitDirRoot), gitDirRoot]);
    continue;
  }
  if (!fs.statSync(dotGit).isDirectory()) { skipped.push(`${name} — .git is a file (worktree/submodule); its hooks live elsewhere, wire them by hand`); continue; }
  if (git(['config', '--local', '--get', 'core.hooksPath'], dir)) { skipped.push(`${name} — has its own local core.hooksPath; a hook written to .git/hooks would never run. Add the guard line to that path yourself`); continue; }
  let own = false;
  try { own = fs.readdirSync(path.join(dotGit, 'hooks')).some((f) => !f.endsWith('.sample') && !readIf(path.join(dotGit, 'hooks', f))?.includes(HOOK_MARK)); } catch { /* no hooks dir */ }
  if (own) reposWithOwnHooks.push(name);
  hookTargets.push([name, dir]);
}

if (GLOBAL) {
  const hooksDir = path.join(HOME_DIR, 'hooks');
  const key = 'core.hooksPath';
  const cur = git(['config', '--global', '--get', key]);
  const ours = fwd(hooksDir);
  if (cur && cur !== ours) {
    skipped.push(`git config --global ${key} is already '${cur}'. NOT replaced — replacing it silently`
      + ' switches off every hook that path holds, and this repo has shipped exactly that bug once.'
      + ' Append the guard line to the pre-commit and pre-push files already there instead.');
  } else {
    if (!fs.existsSync(hooksDir)) {
      steps.push({ line: `CREATE   ${hooksDir}`, do() { fs.mkdirSync(hooksDir, { recursive: true }); record({ action: 'mkdir', path: hooksDir }); } });
    }
    for (const [f, t] of [['pre-commit', pre], ['pre-push', push]]) {
      const dest = path.join(hooksDir, f);
      if (readIf(dest) !== t) steps.push(writeHook(dest, t, `hook-${f}`));
    }
    if (cur !== ours) {
      steps.push({
        line: `SET      git config --global ${key} = '${ours}'`,
        detail: `currently ${cur == null ? '(unset)' : `'${cur}'`} — recorded in the manifest and restored on uninstall. `
          + `This makes the guard run in EVERY repo on this machine`
          + (reposWithOwnHooks.length ? `, and these repos' OWN hooks stop running while it is set: ${reposWithOwnHooks.join(', ')}` : '; no repo here has its own hooks to lose'),
        do() { record({ action: 'git-config-set', key, value: ours, prev: cur ?? null }); git(['config', '--global', key, ours]); },
      });
    }
  }
} else {
  // Per-repo, the default. An existing hook that is not ours is never overwritten and never
  // appended to — editing a file somebody else wrote is a judgment call, and this file does
  // not make judgment calls.
  for (const [name, dir] of hookTargets) {
    for (const [f, t] of [['pre-commit', pre], ['pre-push', push]]) {
      const dest = path.join(dir, '.git', 'hooks', f);
      const cur = readIf(dest);
      if (cur === t) continue;                                    // already ours, current bytes
      if (cur !== null && !cur.includes(HOOK_MARK)) {
        skipped.push(`${name} — ${f} already exists and is not ours. Nothing of yours is ever overwritten; add \`node ${fwd(path.join(HERE, 'bin', 'secret-guard.mjs'))} --${f === 'pre-push' ? 'push' : 'staged'} || exit 1\` to it yourself`);
        continue;
      }
      steps.push(writeHook(dest, t, `hook-${f}`));
    }
  }
}

// -- step: the skills ---------------------------------------------------------------------------
// The kit SHIPPED nine skills and installed none of them — SETUP.md told the reader to copy them
// by hand, which in practice means they sit in a folder doing nothing. Shipping files is not
// shipping behaviour, and the skills are the only part of this kit that changes how the AI
// actually works rather than what it reports. That gap is the same "configured vs fired"
// distinction archetypes.mjs was written to expose, left open inside the installer itself.
//
// Claude Code only, because ~/.claude is its directory. Absent = skipped and SAID, never assumed.
// CLAUDE_CONFIG_DIR is the authority, not ~/.claude. Claude Code reads that variable, and people
// use it precisely to ISOLATE one workspace from their other sessions. Hard-coding the home path
// meant: the nine skills land where this workspace never reads them (inert, while the installer
// reports success), AND they appear in every unrelated session — a change nobody asked for, on a
// machine nobody can debug from here.
//
// Note the shape. The dry run disclosed the true path and the true bytes; it was the CLAIM about
// what the write ACHIEVES that was wrong. That is this kit's defect class in its hardest form:
// it survives perfect disclosure, because the reader checks the facts, finds them accurate, and
// still walks away believing something untrue.
//
// It also only reproduces on a machine where that variable points somewhere non-standard — which
// no CI configures. Found by a reviewer, on her machine, reading a dry run she then declined to
// apply. That is the argument for handing the tool to someone else, made concrete.
const CLAUDE_HOME = process.env.CLAUDE_CONFIG_DIR
  ? path.resolve(process.env.CLAUDE_CONFIG_DIR)
  : path.join(os.homedir(), '.claude');

// THE REVERSIBILITY HOLE. FIVE_HATS_HOME sandboxes the MANIFEST, but the skills destination came
// from CLAUDE_CONFIG_DIR / the real homedir — so a run somebody believed was isolated wrote nine
// live directories and recorded them in a throwaway file. A later `--uninstall` against the real
// home then reported "nothing recorded as installed" while all nine sat there. The undo record
// did not cover everything the tool wrote, which is the same class as every other bug here: a
// record asserting completeness it did not have.
//
// A sandboxed manifest and a live destination cannot both be right. If someone has isolated the
// home, they meant to isolate the run — so refuse rather than write where the undo cannot reach.
if (APPLY && process.env.FIVE_HATS_HOME && !process.env.CLAUDE_CONFIG_DIR
    && fs.existsSync(path.join(os.homedir(), '.claude'))) {
  console.error(`\n  ${B('REFUSING — this run is half-isolated.')}\n`);
  console.error('  FIVE_HATS_HOME is set, so the manifest goes to a sandbox:');
  console.error(`      ${fwd(HOME_DIR)}`);
  console.error('  But CLAUDE_CONFIG_DIR is not, so the skills would go to your REAL config:');
  console.error(`      ${fwd(path.join(os.homedir(), '.claude', 'skills'))}\n`);
  console.error('  Those nine directories would be live, and --uninstall against your real home');
  console.error('  would find no record of them. Set CLAUDE_CONFIG_DIR too, or unset');
  console.error('  FIVE_HATS_HOME — but do not let the undo record cover less than the writes.\n');
  process.exit(2);
}
const CLAUDE_HOME_SOURCE = process.env.CLAUDE_CONFIG_DIR ? 'CLAUDE_CONFIG_DIR' : 'default (~/.claude)';
const SKILLS_SRC = path.join(HERE, 'skills');
const SKILLS_DEST = path.join(CLAUDE_HOME, 'skills');
if (fs.existsSync(SKILLS_SRC)) {
  if (!fs.existsSync(CLAUDE_HOME)) {
    skipped.push(`skills — no ${fwd(CLAUDE_HOME)} on this machine (Claude Code not installed).`
      + ' The tools do not need it; the skills only load there.');
  } else {
    let available = [];
    try { available = fs.readdirSync(SKILLS_SRC).filter((d) => fs.existsSync(path.join(SKILLS_SRC, d, 'SKILL.md'))); }
    catch { available = []; }
    // NEVER overwrite a skill they already have. A name collision is somebody else's work, and
    // silently replacing it is exactly the class of hidden change this installer refuses to make.
    const collisions = available.filter((d) => fs.existsSync(path.join(SKILLS_DEST, d)));
    const fresh = available.filter((d) => !collisions.includes(d));
    if (collisions.length) {
      skipped.push(`${collisions.length} skill(s) already present and NOT overwritten: ${collisions.join(', ')}.`
        + ' Yours stay exactly as they are — compare them by hand if you want ours.');
    }
    for (const d of fresh) {
      const from = path.join(SKILLS_SRC, d, 'SKILL.md');
      const to = path.join(SKILLS_DEST, d, 'SKILL.md');
      const text = readIf(from);
      steps.push({
        line: `WRITE    ${fwd(to)}`,
        // NEVER claim the outcome, only the action — unless the outcome is actually checked.
        // "Loads on a trigger" was true on the author's machine and false on the reviewer's, and
        // no amount of accurate path-and-byte disclosure fixed it: she verified every fact, all
        // of them held, and the sentence still told her she was gaining something she was not.
        // So the claim is now conditional on the thing that makes it true.
        detail: `${Buffer.byteLength(text)} bytes — the "${d}" skill. `
          + `Read from ${CLAUDE_HOME_SOURCE}`
          + (process.env.CLAUDE_CONFIG_DIR
            ? ' — this workspace loads it on a trigger'
            : ' — loads on a trigger in sessions that use the default config dir'),
        do() {
          fs.mkdirSync(path.dirname(to), { recursive: true });
          record({ action: 'write', path: to, kind: `skill-${d}`, sha256: sha(Buffer.from(text)), bytes: Buffer.byteLength(text) });
          fs.writeFileSync(to, text);
        },
      });
    }
  }
}

// ---------------------------------------------------------------------------------------------
// UNDO.md — the by-hand reversal, for the day this file is gone. Rewritten after every apply
// from the manifest, so it describes what actually happened, not what was planned.
// ---------------------------------------------------------------------------------------------
function writeUndo() {
  const { entries } = readManifest();
  const files = entries.filter((e) => e.action === 'write' || e.action === 'copy')
    .map((e) => (e.action === 'copy' ? e.to : e.path));
  const cfg = entries.filter((e) => e.action === 'git-config-set');
  const L = [];
  L.push(`# Undoing the five-hats install (kit ${KIT_VERSION})`);
  L.push('');
  L.push(`Written by install.mjs, last apply ${new Date().toISOString().slice(0, 10)}. The fast way:`);
  L.push('');
  L.push(`    node ${fwd(path.join(HERE, 'install.mjs'))} --uninstall`);
  L.push('');
  L.push('By hand, in this order:');
  L.push('');
  for (const c of cfg) {
    L.push(`1. \`git config --global ${c.prev == null ? `--unset ${c.key}` : `${c.key} '${c.prev}'`}\``);
  }
  L.push(`${cfg.length ? '2' : '1'}. Delete these files (each was written by the installer; nothing else was):`);
  for (const f of [...new Set(files)]) L.push(`   - ${f}`);
  L.push(`${cfg.length ? '3' : '2'}. Delete this folder last — it holds only kit bookkeeping and preserved baseline copies:`);
  L.push(`   - ${HOME_DIR}`);
  L.push('');
  L.push('Nothing else on this machine was changed. Project source was never touched.');
  fs.writeFileSync(UNDO, `${L.join('\n')}\n`);
}

// ---------------------------------------------------------------------------------------------
// SAY IT, then (only on --apply) DO IT.
// ---------------------------------------------------------------------------------------------
console.log(B(`\n  Five Hats — install (kit ${KIT_VERSION})`));
console.log(APPLY ? '' : DIM('  DRY RUN — nothing below has happened yet.\n'));

if (!steps.length) {
  console.log('  Nothing to do — everything below is already in place.\n');
  for (const s of skipped) console.log(`  SKIPPED  ${s}`);
  if (skipped.length) console.log('');
  console.log(DIM(`  Manifest: ${MANIFEST}`));
  console.log(DIM(`  To reverse everything: node install.mjs --uninstall\n`));
  process.exit(0);
}

for (const s of steps) {
  console.log(`  ${s.line}`);
  if (s.detail) console.log(DIM(`           ${s.detail}`));
}
for (const s of skipped) console.log(`  SKIPPED  ${s}`);
console.log(`\n  ${B('WILL NEVER:')} ${never}`);
console.log(DIM(`  Manifest + UNDO.md land in ${HOME_DIR}`));

if (regContent) {
  console.log(`\n  ${B('projects.json, exactly as it will be written:')}\n`);
  console.log(regContent.split('\n').map((l) => `    ${l}`).join('\n'));
}
if (steps.some((s) => /hooks[\\/]pre-commit$/.test(s.line))) {
  console.log(`  ${B('the hook, exactly as it will be written')} (pre-push differs only in its mode):\n`);
  console.log(pre.split('\n').map((l) => `    ${l}`).join('\n'));
}

if (!APPLY) {
  console.log(`  ${B('Nothing above has happened.')} Run again with ${B('--apply')} to do exactly this list —`);
  console.log('  that is the one consent. There are no further prompts, and --uninstall reverses all of it.\n');
  process.exit(0);
}

for (const s of steps) s.do();
writeUndo();
console.log(`\n  ${B('Done.')} ${steps.length} change(s) made, each recorded in the manifest.`);
console.log(`  Reverse everything:  node install.mjs --uninstall`);
console.log(`  By hand if this kit is ever gone:  ${UNDO}\n`);
process.exit(0);
